import re
import requests
from datetime import datetime

from cheki.banks.base import BankVerifier
from cheki.errors import ReceiptNotFoundError, UpstreamError
from cheki.result import VerificationResult, VerificationStatus


class AwashVerifier(BankVerifier):
    """Awash Bank receipt verifier.

    Endpoint: https://awashpay.awashbank.com:8225/-<SHARE_TOKEN>

    The receipt URL uses a share token generated by the Awash app (e.g.
    2KDL95Z0NR-4U61O6). The visible numeric Transaction ID on the mobile
    receipt is NOT the same token and cannot be used directly. Users must
    provide the share URL or the token extracted from it.
    """

    BANK_CODE = "awash"
    BANK_NAME = "Awash Bank"

    def verify(self, reference: str, **kwargs: object) -> VerificationResult:
        # Accept either a full share URL or just the token
        token = reference.strip()
        if token.startswith("https://awashpay.awashbank.com:8225/-"):
            token = token.split("/-", 1)[1]

        url = f"https://awashpay.awashbank.com:8225/-{token}"

        try:
            resp = self._get(url, verify=False)
        except requests.RequestException as exc:
            raise UpstreamError(f"Awash receipt endpoint could not be reached: {exc}")

        if resp.status_code != 200 or "Invalid receipt id" in resp.text:
            raise ReceiptNotFoundError("Awash did not find a receipt for this reference.")

        parsed = self._parse_html(resp.text)
        if not parsed["verified"]:
            raise ReceiptNotFoundError("Awash did not find a receipt for this reference.")

        return VerificationResult(
            bank=self.BANK_CODE,
            reference=parsed["reference"] or token,
            status=VerificationStatus.VERIFIED,
            exists=True,
            amount=parsed["amount"],
            currency="ETB",
            sender_name=parsed["sender_name"],
            sender_account=parsed["sender_account"],
            receiver_name=parsed["receiver_name"],
            receiver_account=parsed["receiver_account"],
            transaction_date=parsed["transaction_date"],
            source_url=url,
            raw=parsed,
            message="Awash receipt verified.",
        )

    def _parse_html(self, html: str) -> dict:
        # Strip scripts and styles, then extract text lines
        text = re.sub(r"<script[^>]*>[\s\S]*?</script>", "", html, flags=re.IGNORECASE)
        text = re.sub(r"<style[^>]*>[\s\S]*?</style>", "", text, flags=re.IGNORECASE)
        text = re.sub(r"<[^>]+>", "\n", text)
        lines = [line.strip() for line in text.split("\n") if line.strip()]

        def find_value(label: str) -> str | None:
            for i, line in enumerate(lines):
                if label.lower() in line.lower():
                    # Check same line after the label
                    same_line = re.sub(rf"^.*?{re.escape(label)}\s*:?\s*", "", line, flags=re.IGNORECASE).strip()
                    if same_line:
                        return same_line
                    # Value on next line(s)
                    j = i + 1
                    if j < len(lines) and lines[j] == ":":
                        j += 1
                    if j < len(lines):
                        return lines[j]
            return None

        sender_name = find_value("Sender Name") or find_value("Customer Name")
        sender_account = find_value("Sender Account") or find_value("Account No")
        receiver_name = find_value("Receiver Name")
        receiver_account = find_value("Receiver Account")
        reason = find_value("Reason")
        branch = find_value("Branch")
        transaction_type = find_value("Transaction Type")
        transaction_id = find_value("Transaction ID")
        date_str = find_value("Transaction Date")

        amount = None
        amount_str = find_value("Amount")
        if amount_str:
            m = re.search(r"(\d+(?:\.\d+)?)", amount_str.replace(",", ""))
            if m:
                amount = float(m.group(1))

        transaction_date = None
        if date_str:
            try:
                transaction_date = datetime.strptime(date_str, "%Y-%m-%d %H:%M:%S")
            except ValueError:
                transaction_date = None

        verified = (
            sender_name is not None
            and sender_account is not None
            and receiver_name is not None
            and receiver_account is not None
            and amount is not None
            and transaction_date is not None
        )

        return {
            "verified": verified,
            "reference": transaction_id,
            "sender_name": sender_name,
            "sender_account": sender_account,
            "receiver_name": receiver_name,
            "receiver_account": receiver_account,
            "amount": amount,
            "currency": "ETB",
            "transaction_date": transaction_date,
            "branch": branch,
            "reason": reason,
            "transaction_type": transaction_type,
            "raw_lines": lines,
        }
